debug: true
server:
  port: 8888

security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /dashboard/login
management:
  security:
    role: HERO
logging:
  level:
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: gordon
      clientSecret: gordon
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3GQnV+yCVWNj8X/perOV
          U3opPwMX9YnUXbueMNsOYejXF7DFIZvPP2ZeofrQkAwAjW6TC8PVMEJS5RYugjy+
          chzyBj5sYCyn/vtUst4B4MVrsswO5gFyAXW+RkqySVRI3tU+Y/qRe2pAcDiuJ5V7
          jybRxneQY0AcHwSF1uoE1FY6DXObSy9bl9xspzLWxIXpmK1a2+E8Ix7Zhs7TtXNJ
          US1DcP5k48M+KdKgp2dstwJHn//rpC343iXPDnpESqJgWi03bP3idTn10SDmC514
          Dv2f7l2xQ/ux3GfKqdgmST9VB8/8xwkaX7AOJPMEjo6+8PRnO4uHGPYv+QNtEYE0
          BwIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

---
spring:
  profiles: github
security:
  oauth2:
    client:
      clientId: 89630a412fa314777dc2
      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

---
spring:
  profiles: wso2
security:
  oauth2:
    client:
      clientId: k3SXxgWd3B5GU2j4uwRHnunQ2P4a
      clientSecret: mcOOSkTHgybIqBFt_gTfII702t4a
      accessTokenUri: https://wso2idserver.local:9443/oauth2/token
      userAuthorizationUri: https://wso2idserver.local:9443/oauth2/authorize
      scope: openid
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://wso2idserver.local:9443/oauth2/userinfo?schema=openid
      token-type: openid
      preferTokenInfo: false
